import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';


const axiforma = localFont({
  src: [
    {
      path: './fonts/Axiforma-Black.woff',
      weight: '900',
      style: 'normal',
    },
    {
      path: './fonts/Axiforma-ExtraBold.woff',
      weight: '800',
      style: 'normal',
    },
    {
      path: './fonts/Axiforma-Bold.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Axiforma-SemiBold.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Axiforma-Medium.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Axiforma-Regular.woff',
      weight: '400',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${axiforma.className} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
